### PR TITLE
show finish stepNumber

### PR DESCRIPTION
**Pull request by yoyo837**
Show finish step number. Or provide optional configuration?

### CODE REVIEW

**Comment by mribbons** [comment]
@afc163 Any plans to accept this PR, or can you suggest how to do it optionally as per @yoyo837?

**Comment by ebaker** [comment]
bumping as this feature is desired. what prevented the merge before?

**Comment by afc163** [comment]
It will be a break change, a option would be good.

**Comment by yoyo837** [comment]
#74

**Pull request closed without merging**
