### PR TITLE
Rewrite steps

### PR DESCRIPTION
**Pull request by afc163**
close https://github.com/react-component/steps/issues/38

- [x] Use flex
- [x] Do not show after mount
- [x] IE9 compatibility
- [x] Simpler dom structure
- [x] Rewrite styles
- [x] Upgrade rc-tools
- [x] Can be used on different background
- [x] Add test cases

### CODE REVIEW

**Comment by afc163** [comment]
整个重写了 Steps，解决了延迟渲染和背景色问题。

**Comment by benjycui** [comment]
例子都挂了。。 http://react-component.github.io/steps/examples/alternativeLabel.html

**Comment by afc163** [comment]
Fixed in 34d80fc and `3.0.1`.

**Comment by afc163** [comment]
发现 npm run pub 没有发 npm。

**Comment by afc163** [comment]
package.json 里的 config.entry 是啥？

为啥 rc-select 没有这个也能发布？

https://github.com/react-component/select/blob/master/package.json#L27-L29

**Comment by paranoidjk** [comment]
@afc163 https://github.com/react-component/react-component.github.io/issues/14 config.entry 是 @yiminghe 在 rc-tools 新版本做的一个 break change，没有的话不会 build umd dist

**Pull request merged**
